environment: development
name: azure-event-hubs-kafka-client
image: johnwatson484.azurecr.io/azure-event-hubs-kafka-client

container:
  imagePullPolicy: Always
  requestMemory: 60Mi
  requestCpu: 60m
  limitMemory: 60Mi
  limitCpu: 60m
  readOnlyRootFilesystem: false
  allowPrivilegeEscalation: false
  eventHubHost:
  eventHubConnectionString:
  eventHubAuth: token
  eventHubTopic: ffc-demo-claim-update

deployment:
  replicas: 1
  minReadySeconds: 0
  redeployOnChange: update this field to force da change
  runAsNonRoot: true
  runAsUser: 1000

azureIdentity:
  resourceID:
  clientID:

aadPodIdentity: true
