{{- if .Values.aadPodIdentity }}
{{- include "helm-library.azure-identity-binding" (list . "azure-event-hubs-kafka-client.azure-identity-binding") -}}
{{- end }}
{{- define "azure-event-hubs-kafka-client.azure-identity-binding" -}}
{{- end -}}
